export interface BlockchainInfo {
  id: string;
  name: string;
  symbol: string;
  icon: string;
  color: string;
  category: 'Layer1' | 'Layer2' | 'Sidechain';
  explorer: string;
  description: string;
}

export const BLOCKCHAINS: BlockchainInfo[] = [
  // Top Layer 1 Chains
  { id: 'BITCOIN', name: 'Bitcoin', symbol: 'BTC', icon: '₿', color: '#F7931A', category: 'Layer1', explorer: 'blockchain.com', description: 'Original cryptocurrency' },
  { id: 'ETHEREUM', name: 'Ethereum', symbol: 'ETH', icon: 'Ξ', color: '#627EEA', category: 'Layer1', explorer: 'etherscan.io', description: 'Smart contract platform' },
  { id: 'SOLANA', name: 'Solana', symbol: 'SOL', icon: '◎', color: '#14F195', category: 'Layer1', explorer: 'solscan.io', description: 'High-performance blockchain' },
  { id: 'CARDANO', name: 'Cardano', symbol: 'ADA', icon: '₳', color: '#0033AD', category: 'Layer1', explorer: 'cardanoscan.io', description: 'Proof-of-stake blockchain' },
  { id: 'POLKADOT', name: 'Polkadot', symbol: 'DOT', icon: '●', color: '#E6007A', category: 'Layer1', explorer: 'polkascan.io', description: 'Multi-chain protocol' },
  { id: 'AVALANCHE', name: 'Avalanche', symbol: 'AVAX', icon: '▲', color: '#E84142', category: 'Layer1', explorer: 'snowtrace.io', description: 'Fast smart contracts' },
  { id: 'COSMOS', name: 'Cosmos', symbol: 'ATOM', icon: '⚛', color: '#2E3148', category: 'Layer1', explorer: 'mintscan.io', description: 'Internet of blockchains' },
  { id: 'ALGORAND', name: 'Algorand', symbol: 'ALGO', icon: '◆', color: '#000000', category: 'Layer1', explorer: 'algoexplorer.io', description: 'Pure proof-of-stake' },
  { id: 'TEZOS', name: 'Tezos', symbol: 'XTZ', icon: 'ꜩ', color: '#2C7DF7', category: 'Layer1', explorer: 'tzstats.com', description: 'Self-amending blockchain' },
  { id: 'NEAR', name: 'NEAR Protocol', symbol: 'NEAR', icon: 'Ⓝ', color: '#00C08B', category: 'Layer1', explorer: 'explorer.near.org', description: 'Sharded blockchain' },
  { id: 'APTOS', name: 'Aptos', symbol: 'APT', icon: '🅰', color: '#00D4AA', category: 'Layer1', explorer: 'aptoscan.com', description: 'Move-based blockchain' },
  { id: 'SUI', name: 'Sui', symbol: 'SUI', icon: '🌊', color: '#4DA2FF', category: 'Layer1', explorer: 'suiscan.xyz', description: 'Next-gen smart contracts' },
  { id: 'HEDERA', name: 'Hedera', symbol: 'HBAR', icon: 'ℏ', color: '#000000', category: 'Layer1', explorer: 'hashscan.io', description: 'Hashgraph consensus' },
  { id: 'TRON', name: 'Tron', symbol: 'TRX', icon: '⚡', color: '#FF0013', category: 'Layer1', explorer: 'tronscan.org', description: 'Decentralized internet' },
  { id: 'RIPPLE', name: 'Ripple', symbol: 'XRP', icon: '✕', color: '#23292F', category: 'Layer1', explorer: 'xrpscan.com', description: 'Payment protocol' },
  { id: 'STELLAR', name: 'Stellar', symbol: 'XLM', icon: '⭐', color: '#000000', category: 'Layer1', explorer: 'stellarchain.io', description: 'Cross-border payments' },
  { id: 'LITECOIN', name: 'Litecoin', symbol: 'LTC', icon: 'Ł', color: '#345D9D', category: 'Layer1', explorer: 'blockchair.com/litecoin', description: 'Silver to Bitcoin gold' },
  { id: 'MONERO', name: 'Monero', symbol: 'XMR', icon: 'Ɯ', color: '#FF6600', category: 'Layer1', explorer: 'xmrchain.net', description: 'Privacy-focused cryptocurrency' },
  { id: 'ZCASH', name: 'Zcash', symbol: 'ZEC', icon: 'Ẓ', color: '#ECB244', category: 'Layer1', explorer: 'zcashblockexplorer.com', description: 'Privacy coin with shielded transactions' },
  { id: 'DASH', name: 'Dash', symbol: 'DASH', icon: 'Đ', color: '#008CE7', category: 'Layer1', explorer: 'explorer.dash.org', description: 'Digital cash' },
  { id: 'ETHEREUM_CLASSIC', name: 'Ethereum Classic', symbol: 'ETC', icon: 'Ξ', color: '#328332', category: 'Layer1', explorer: 'etcblockexplorer.com', description: 'Original Ethereum chain' },
  { id: 'FANTOM', name: 'Fantom', symbol: 'FTM', icon: '👻', color: '#1969FF', category: 'Layer1', explorer: 'ftmscan.com', description: 'DAG-based platform' },
  { id: 'CELO', name: 'Celo', symbol: 'CELO', icon: '🌱', color: '#FBCC5C', category: 'Layer1', explorer: 'celoscan.io', description: 'Mobile-first blockchain' },
  { id: 'CHAINLINK', name: 'Chainlink', symbol: 'LINK', icon: '🔗', color: '#2A5ADA', category: 'Layer1', explorer: 'etherscan.io', description: 'Decentralized oracle network' },
  { id: 'FILECOIN', name: 'Filecoin', symbol: 'FIL', icon: '💾', color: '#0090FF', category: 'Layer1', explorer: 'filfox.info', description: 'Decentralized storage' },
  { id: 'VET', name: 'VeChain', symbol: 'VET', icon: 'Ⓥ', color: '#15BDFF', category: 'Layer1', explorer: 'vechainstats.com', description: 'Supply chain blockchain' },
  { id: 'THETA', name: 'Theta Network', symbol: 'THETA', icon: 'Θ', color: '#2AB8E6', category: 'Layer1', explorer: 'explorer.thetatoken.org', description: 'Video streaming blockchain' },
  { id: 'ELROND', name: 'MultiversX', symbol: 'EGLD', icon: 'Ⓔ', color: '#000000', category: 'Layer1', explorer: 'explorer.multiversx.com', description: 'Internet-scale blockchain' },
  { id: 'FLOW', name: 'Flow', symbol: 'FLOW', icon: '🌊', color: '#00EF8B', category: 'Layer1', explorer: 'flowscan.org', description: 'NFT and gaming blockchain' },
  { id: 'HARMONY', name: 'Harmony', symbol: 'ONE', icon: '①', color: '#00ADE8', category: 'Layer1', explorer: 'explorer.harmony.one', description: 'Sharding-based blockchain' },
  { id: 'ZILLIQA', name: 'Zilliqa', symbol: 'ZIL', icon: 'Ⓩ', color: '#49C1BF', category: 'Layer1', explorer: 'viewblock.io/zilliqa', description: 'High-throughput blockchain' },
  { id: 'WAVES', name: 'Waves', symbol: 'WAVES', icon: '🌊', color: '#0155FF', category: 'Layer1', explorer: 'wavesexplorer.com', description: 'Multi-purpose blockchain' },
  { id: 'ICON', name: 'ICON', symbol: 'ICX', icon: 'Ⓘ', color: '#1FC5C9', category: 'Layer1', explorer: 'tracker.icon.community', description: 'Blockchain interoperability' },
  { id: 'ONTOLOGY', name: 'Ontology', symbol: 'ONT', icon: 'Ⓞ', color: '#32A4BE', category: 'Layer1', explorer: 'explorer.ont.io', description: 'High-performance public blockchain' },
  { id: 'QTUM', name: 'Qtum', symbol: 'QTUM', icon: 'Ⓠ', color: '#2E9AD0', category: 'Layer1', explorer: 'qtum.info', description: 'Hybrid blockchain' },
  { id: 'KLAYTN', name: 'Klaytn', symbol: 'KLAY', icon: '🌸', color: '#FF3D00', category: 'Layer1', explorer: 'scope.klaytn.com', description: 'Kakao blockchain' },
  { id: 'OASIS', name: 'Oasis Network', symbol: 'ROSE', icon: '🌹', color: '#0092F6', category: 'Layer1', explorer: 'explorer.oasis.io', description: 'Privacy-enabled blockchain' },
  { id: 'IOTA', name: 'IOTA', symbol: 'MIOTA', icon: 'ℹ', color: '#131F37', category: 'Layer1', explorer: 'explorer.iota.org', description: 'Tangle DAG technology' },
  { id: 'NEO', name: 'Neo', symbol: 'NEO', icon: 'Ⓝ', color: '#58BF00', category: 'Layer1', explorer: 'neoscan.io', description: 'Smart economy platform' },
  { id: 'EOS', name: 'EOS', symbol: 'EOS', icon: 'Ⓔ', color: '#000000', category: 'Layer1', explorer: 'bloks.io', description: 'Delegated proof-of-stake' },
  { id: 'KUSAMA', name: 'Kusama', symbol: 'KSM', icon: '🐦', color: '#000000', category: 'Layer1', explorer: 'kusama.subscan.io', description: 'Polkadot canary network' },
  { id: 'ASTAR', name: 'Astar', symbol: 'ASTR', icon: '⭐', color: '#0AE2FF', category: 'Layer1', explorer: 'astar.subscan.io', description: 'Polkadot smart contracts' },
  { id: 'MOONRIVER', name: 'Moonriver', symbol: 'MOVR', icon: '🌙', color: '#F2B705', category: 'Sidechain', explorer: 'moonriver.moonscan.io', description: 'Kusama parachain' },
  { id: 'MOONBEAM', name: 'Moonbeam', symbol: 'GLMR', icon: '🌙', color: '#53CBC9', category: 'Sidechain', explorer: 'moonscan.io', description: 'Polkadot parachain' },
  { id: 'ACALA', name: 'Acala', symbol: 'ACA', icon: '🦀', color: '#E40C5B', category: 'Layer1', explorer: 'acala.subscan.io', description: 'Polkadot DeFi hub' },
  { id: 'KARURA', name: 'Karura', symbol: 'KAR', icon: '🦐', color: '#FF4C3B', category: 'Layer1', explorer: 'karura.subscan.io', description: 'Kusama DeFi hub' },
  { id: 'PARALLEL', name: 'Parallel', symbol: 'PARA', icon: '⫿', color: '#F9475E', category: 'Layer1', explorer: 'parallel.subscan.io', description: 'Polkadot lending' },
  { id: 'BIFROST', name: 'Bifrost', symbol: 'BNC', icon: '🌈', color: '#5A25F0', category: 'Layer1', explorer: 'bifrost.subscan.io', description: 'Liquid staking' },
  { id: 'PHALA', name: 'Phala Network', symbol: 'PHA', icon: '🔐', color: '#CDFA50', category: 'Layer1', explorer: 'phala.subscan.io', description: 'Confidential smart contracts' },
  { id: 'CENTRIFUGE', name: 'Centrifuge', symbol: 'CFG', icon: '⚙', color: '#2762FF', category: 'Layer1', explorer: 'centrifuge.subscan.io', description: 'Real-world assets' },
  { id: 'INTERLAY', name: 'Interlay', symbol: 'INTR', icon: '₿', color: '#3E96FF', category: 'Layer1', explorer: 'interlay.subscan.io', description: 'Bitcoin on Polkadot' },
  { id: 'KINTSUGI', name: 'Kintsugi', symbol: 'KINT', icon: '🏺', color: '#ECC13A', category: 'Layer1', explorer: 'kintsugi.subscan.io', description: 'Bitcoin on Kusama' },
  
  // Cosmos Ecosystem (50+ chains)
  { id: 'KAVA', name: 'Kava', symbol: 'KAVA', icon: '🌿', color: '#FF564F', category: 'Layer1', explorer: 'mintscan.io/kava', description: 'DeFi for crypto' },
  { id: 'BAND', name: 'Band Protocol', symbol: 'BAND', icon: '🎵', color: '#516BFF', category: 'Layer1', explorer: 'cosmoscan.io', description: 'Cross-chain data oracle' },
  { id: 'INJECTIVE', name: 'Injective', symbol: 'INJ', icon: '⚡', color: '#00F2FE', category: 'Layer1', explorer: 'explorer.injective.network', description: 'DeFi blockchain' },
  { id: 'OSMOSIS', name: 'Osmosis', symbol: 'OSMO', icon: '🧪', color: '#5E12A0', category: 'Layer1', explorer: 'mintscan.io/osmosis', description: 'DEX protocol' },
  { id: 'JUNO', name: 'Juno', symbol: 'JUNO', icon: '🪐', color: '#F0827D', category: 'Layer1', explorer: 'mintscan.io/juno', description: 'Interoperable smart contracts' },
  { id: 'STARGAZE', name: 'Stargaze', symbol: 'STARS', icon: '⭐', color: '#DB2777', category: 'Layer1', explorer: 'mintscan.io/stargaze', description: 'NFT marketplace chain' },
  { id: 'AKASH', name: 'Akash Network', symbol: 'AKT', icon: '☁️', color: '#FF414C', category: 'Layer1', explorer: 'mintscan.io/akash', description: 'Decentralized cloud' },
  { id: 'SECRET', name: 'Secret Network', symbol: 'SCRT', icon: '🔒', color: '#000000', category: 'Layer1', explorer: 'mintscan.io/secret', description: 'Privacy-preserving smart contracts' },
  { id: 'TERRA', name: 'Terra Classic', symbol: 'LUNC', icon: '🌍', color: '#FFD83D', category: 'Layer1', explorer: 'finder.terra.money', description: 'Algorithmic stablecoin platform' },
  { id: 'KUJIRA', name: 'Kujira', symbol: 'KUJI', icon: '🐳', color: '#E74C3C', category: 'Layer1', explorer: 'finder.kujira.app', description: 'DeFi hub' },
  { id: 'EVMOS', name: 'Evmos', symbol: 'EVMOS', icon: '🔥', color: '#ED4E33', category: 'Layer1', explorer: 'mintscan.io/evmos', description: 'EVM on Cosmos' },
  { id: 'AXELAR', name: 'Axelar', symbol: 'AXL', icon: '🌐', color: '#000000', category: 'Layer1', explorer: 'axelarscan.io', description: 'Cross-chain communication' },
  { id: 'CELESTIA', name: 'Celestia', symbol: 'TIA', icon: '🌠', color: '#7B2BF9', category: 'Layer1', explorer: 'celenium.io', description: 'Modular blockchain' },
  { id: 'SEI', name: 'Sei Network', symbol: 'SEI', icon: '⚡', color: '#B91C1C', category: 'Layer1', explorer: 'seiscan.app', description: 'Fastest Layer 1' },
  { id: 'NEUTRON', name: 'Neutron', symbol: 'NTRN', icon: '⚛️', color: '#000000', category: 'Layer1', explorer: 'mintscan.io/neutron', description: 'Smart contract platform' },
  { id: 'DYDX', name: 'dYdX Chain', symbol: 'DYDX', icon: '📈', color: '#6966FF', category: 'Layer1', explorer: 'mintscan.io/dydx', description: 'Decentralized exchange' },
  { id: 'STRIDE', name: 'Stride', symbol: 'STRD', icon: '🏃', color: '#E50571', category: 'Layer1', explorer: 'mintscan.io/stride', description: 'Liquid staking' },
  { id: 'COMDEX', name: 'Comdex', symbol: 'CMDX', icon: '💼', color: '#FC4747', category: 'Layer1', explorer: 'mintscan.io/comdex', description: 'DeFi infrastructure' },
  { id: 'CRESCENT', name: 'Crescent', symbol: 'CRE', icon: '🌙', color: '#4ECDC4', category: 'Layer1', explorer: 'mintscan.io/crescent', description: 'DeFi hub' },
  { id: 'UMEE', name: 'Umee', symbol: 'UMEE', icon: '🌉', color: '#6B46C1', category: 'Layer1', explorer: 'mintscan.io/umee', description: 'Cross-chain DeFi' },
  { id: 'SOMMELIER', name: 'Sommelier', symbol: 'SOMM', icon: '🍷', color: '#F24C4C', category: 'Layer1', explorer: 'mintscan.io/sommelier', description: 'DeFi strategies' },
  { id: 'QUICKSILVER', name: 'Quicksilver', symbol: 'QCK', icon: '⚡', color: '#E42575', category: 'Layer1', explorer: 'mintscan.io/quicksilver', description: 'Liquid staking zone' },
  { id: 'PERSISTENCE', name: 'Persistence', symbol: 'XPRT', icon: '🔗', color: '#E42575', category: 'Layer1', explorer: 'mintscan.io/persistence', description: 'Liquid staking' },
  { id: 'REGEN', name: 'Regen Network', symbol: 'REGEN', icon: '🌱', color: '#4FB573', category: 'Layer1', explorer: 'mintscan.io/regen', description: 'Climate solutions' },
  { id: 'SENTINEL', name: 'Sentinel', symbol: 'DVPN', icon: '🛡️', color: '#1B4965', category: 'Layer1', explorer: 'mintscan.io/sentinel', description: 'Decentralized VPN' },
  { id: 'CHIHUAHUA', name: 'Chihuahua', symbol: 'HUAHUA', icon: '🐕', color: '#F4A460', category: 'Layer1', explorer: 'mintscan.io/chihuahua', description: 'Meme chain' },
  { id: 'BITCANNA', name: 'BitCanna', symbol: 'BCNA', icon: '🌿', color: '#00D494', category: 'Layer1', explorer: 'mintscan.io/bitcanna', description: 'Cannabis industry' },
  { id: 'DESMOS', name: 'Desmos', symbol: 'DSM', icon: '💬', color: '#FF3C6C', category: 'Layer1', explorer: 'mintscan.io/desmos', description: 'Social network' },
  { id: 'LIKECOIN', name: 'LikeCoin', symbol: 'LIKE', icon: '👍', color: '#28646E', category: 'Layer1', explorer: 'likecoin.bigdipper.live', description: 'Content creators' },
  { id: 'IRIS', name: 'IRISnet', symbol: 'IRIS', icon: '🌺', color: '#3442D9', category: 'Layer1', explorer: 'irishub.iobscan.io', description: 'Service hub' },
  { id: 'EMONEY', name: 'e-Money', symbol: 'NGM', icon: '💶', color: '#1B3D6D', category: 'Layer1', explorer: 'emoney.bigdipper.live', description: 'Currency-backed tokens' },
  { id: 'SIFCHAIN', name: 'Sifchain', symbol: 'ROWAN', icon: '🌳', color: '#D4AF37', category: 'Layer1', explorer: 'sifchain.network', description: 'Omni-chain DEX' },
  { id: 'KONSTELLATION', name: 'Konstellation', symbol: 'DARC', icon: '🌌', color: '#4A90E2', category: 'Layer1', explorer: 'mintscan.io/konstellation', description: 'DeFi capital markets' },
  { id: 'RIZON', name: 'Rizon', symbol: 'ATOLO', icon: '🔷', color: '#00A3E0', category: 'Layer1', explorer: 'mintscan.io/rizon', description: 'Digital assets hub' },
  { id: 'PROVENANCE', name: 'Provenance', symbol: 'HASH', icon: '#', color: '#1C4E80', category: 'Layer1', explorer: 'explorer.provenance.io', description: 'Financial services' },
  { id: 'CHEQD', name: 'cheqd', symbol: 'CHEQ', icon: '✓', color: '#FC6A3D', category: 'Layer1', explorer: 'explorer.cheqd.io', description: 'Decentralized identity' },
  { id: 'ASSETMANTLE', name: 'AssetMantle', symbol: 'MNTL', icon: '🎨', color: '#FF6B35', category: 'Layer1', explorer: 'mintscan.io/asset-mantle', description: 'NFT marketplace' },
  { id: 'FETCHAI', name: 'Fetch.ai', symbol: 'FET', icon: '🤖', color: '#1A1A2E', category: 'Layer1', explorer: 'mintscan.io/fetchai', description: 'AI agents' },
  { id: 'KI', name: 'Ki Chain', symbol: 'XKI', icon: '⚛️', color: '#00D2FF', category: 'Layer1', explorer: 'mintscan.io/ki-chain', description: 'DeFi hub' },
  { id: 'MEDIBLOC', name: 'MediBloc', symbol: 'MED', icon: '⚕️', color: '#0099CC', category: 'Layer1', explorer: 'explorer.medibloc.org', description: 'Healthcare data' },
  { id: 'BITSONG', name: 'BitSong', symbol: 'BTSG', icon: '🎵', color: '#FF006E', category: 'Layer1', explorer: 'mintscan.io/bitsong', description: 'Music streaming' },
  { id: 'LUMENX', name: 'LumenX', symbol: 'LUMEN', icon: '💡', color: '#FFD700', category: 'Layer1', explorer: 'mintscan.io/lumenx', description: 'Energy trading' },
  { id: 'VIDULUM', name: 'Vidulum', symbol: 'VDL', icon: '🔐', color: '#6C5CE7', category: 'Layer1', explorer: 'explorers.vidulum.app', description: 'Multi-asset wallet' },
  { id: 'DECENTR', name: 'Decentr', symbol: 'DEC', icon: '🌐', color: '#00B4D8', category: 'Layer1', explorer: 'explorer.decentr.net', description: 'Data value' },
  { id: 'CERBERUS', name: 'Cerberus', symbol: 'CRBRUS', icon: '🐺', color: '#8B0000', category: 'Layer1', explorer: 'explorer.cerberus.zone', description: 'DeFi protocols' },
  { id: 'OMNIFLIX', name: 'OmniFlix', symbol: 'FLIX', icon: '🎬', color: '#FF4081', category: 'Layer1', explorer: 'mintscan.io/omniflix', description: 'Media network' },
  { id: 'PASSAGE', name: 'Passage', symbol: 'PASG', icon: '🎮', color: '#9C27B0', category: 'Layer1', explorer: 'mintscan.io/passage', description: 'Metaverse' },
  { id: 'TERITORI', name: 'Teritori', symbol: 'TORI', icon: '🏝️', color: '#00BFA5', category: 'Layer1', explorer: 'explorer.teritori.com', description: 'Multi-chain hub' },
  { id: 'ARCHWAY', name: 'Archway', symbol: 'ARCH', icon: '🏛️', color: '#FF6B35', category: 'Layer1', explorer: 'mintscan.io/archway', description: 'Rewards protocol' },
  { id: 'JACKAL', name: 'Jackal Protocol', symbol: 'JKL', icon: '🦊', color: '#FF8C00', category: 'Layer1', explorer: 'ping.pub/jackal', description: 'Decentralized storage' },
  { id: 'MIGALOO', name: 'Migaloo', symbol: 'WHALE', icon: '🐋', color: '#0077BE', category: 'Layer1', explorer: 'inbloc.org/migaloo', description: 'Liquidity layer' },
  { id: 'NOLUS', name: 'Nolus', symbol: 'NLS', icon: '💰', color: '#4169E1', category: 'Layer1', explorer: 'explorer.nolus.io', description: 'DeFi lease' },
  { id: 'QUASAR', name: 'Quasar', symbol: 'QSR', icon: '✨', color: '#9D4EDD', category: 'Layer1', explorer: 'mintscan.io/quasar', description: 'Interchain vaults' },
  { id: 'COMPOSABLE', name: 'Composable', symbol: 'PICA', icon: '🎨', color: '#FF1493', category: 'Layer1', explorer: 'composable.subscan.io', description: 'Cross-chain DeFi' },
  
  // Layer 2 Solutions (40+ chains)
  { id: 'POLYGON', name: 'Polygon', symbol: 'MATIC', icon: '⬡', color: '#8247E5', category: 'Layer2', explorer: 'polygonscan.com', description: 'Ethereum scaling' },
  { id: 'ARBITRUM', name: 'Arbitrum', symbol: 'ARB', icon: '🔷', color: '#28A0F0', category: 'Layer2', explorer: 'arbiscan.io', description: 'Optimistic rollup' },
  { id: 'OPTIMISM', name: 'Optimism', symbol: 'OP', icon: '🔴', color: '#FF0420', category: 'Layer2', explorer: 'optimistic.etherscan.io', description: 'Ethereum L2' },
  { id: 'BASE', name: 'Base', symbol: 'BASE', icon: '🔵', color: '#0052FF', category: 'Layer2', explorer: 'basescan.org', description: 'Coinbase L2' },
  { id: 'ZKSYNC', name: 'zkSync Era', symbol: 'ZK', icon: '⚡', color: '#8C8DFC', category: 'Layer2', explorer: 'explorer.zksync.io', description: 'ZK rollup' },
  { id: 'STARKNET', name: 'Starknet', symbol: 'STRK', icon: '🔷', color: '#EC796B', category: 'Layer2', explorer: 'starkscan.co', description: 'ZK-STARK L2' },
  { id: 'SCROLL', name: 'Scroll', symbol: 'SCR', icon: '📜', color: '#FFEEDA', category: 'Layer2', explorer: 'scrollscan.com', description: 'ZK-EVM rollup' },
  { id: 'LINEA', name: 'Linea', symbol: 'LINEA', icon: '🟦', color: '#121212', category: 'Layer2', explorer: 'lineascan.build', description: 'ConsenSys zkEVM' },
  { id: 'MANTA', name: 'Manta Pacific', symbol: 'MANTA', icon: '🧜', color: '#1B4965', category: 'Layer2', explorer: 'pacific-explorer.manta.network', description: 'Modular L2' },
  { id: 'BLAST', name: 'Blast', symbol: 'BLAST', icon: '💥', color: '#FCFC03', category: 'Layer2', explorer: 'blastscan.io', description: 'Native yield L2' },
  { id: 'IMMUTABLE', name: 'Immutable X', symbol: 'IMX', icon: '🎮', color: '#0B0E11', category: 'Layer2', explorer: 'immutascan.io', description: 'NFT L2' },
  { id: 'METIS', name: 'Metis', symbol: 'METIS', icon: 'Ⓜ️', color: '#00DACC', category: 'Layer2', explorer: 'andromeda-explorer.metis.io', description: 'Optimistic rollup' },
  { id: 'BOBA', name: 'Boba Network', symbol: 'BOBA', icon: '🧋', color: '#CBFF00', category: 'Layer2', explorer: 'bobascan.com', description: 'Hybrid compute' },
  { id: 'LOOPRING', name: 'Loopring', symbol: 'LRC', icon: '⭕', color: '#1C60FF', category: 'Layer2', explorer: 'explorer.loopring.io', description: 'ZK rollup DEX' },
  { id: 'AZTEC', name: 'Aztec', symbol: 'AZTEC', icon: '🔺', color: '#000000', category: 'Layer2', explorer: 'aztec.network', description: 'Privacy L2' },
  { id: 'POLYGON_ZKEVM', name: 'Polygon zkEVM', symbol: 'ZKEVM', icon: '⬢', color: '#7B3FE4', category: 'Layer2', explorer: 'zkevm.polygonscan.com', description: 'ZK-EVM' },
  { id: 'TAIKO', name: 'Taiko', symbol: 'TAIKO', icon: '🥁', color: '#E81899', category: 'Layer2', explorer: 'taikoscan.io', description: 'Based rollup' },
  { id: 'MODE', name: 'Mode Network', symbol: 'MODE', icon: '🟢', color: '#DFFE00', category: 'Layer2', explorer: 'explorer.mode.network', description: 'OP Stack L2' },
  { id: 'ZORA', name: 'Zora', symbol: 'ZORA', icon: '⚫', color: '#000000', category: 'Layer2', explorer: 'explorer.zora.energy', description: 'NFT L2' },
  { id: 'MANTLE', name: 'Mantle', symbol: 'MNT', icon: '🔷', color: '#000000', category: 'Layer2', explorer: 'explorer.mantle.xyz', description: 'Modular L2' },
  { id: 'CANTO', name: 'Canto', symbol: 'CANTO', icon: '🎵', color: '#06FC99', category: 'Layer1', explorer: 'tuber.build', description: 'Free public infrastructure' },
  { id: 'KROMA', name: 'Kroma', symbol: 'KRO', icon: '🌈', color: '#FF6B6B', category: 'Layer2', explorer: 'kromascan.com', description: 'Universal ZK rollup' },
  { id: 'OPBNB', name: 'opBNB', symbol: 'OPBNB', icon: '⚡', color: '#F0B90B', category: 'Layer2', explorer: 'opbnbscan.com', description: 'BNB L2' },
  { id: 'ZKFAIR', name: 'ZKFair', symbol: 'ZKF', icon: '⚖️', color: '#00D4AA', category: 'Layer2', explorer: 'scan.zkfair.io', description: 'Community ZK-L2' },
  { id: 'AEVO', name: 'Aevo', symbol: 'AEVO', icon: '📊', color: '#0052FF', category: 'Layer2', explorer: 'explorer.aevo.xyz', description: 'Options trading' },
  { id: 'LYRA', name: 'Lyra', symbol: 'LYRA', icon: '🎼', color: '#00D9FF', category: 'Layer2', explorer: 'explorer.lyra.finance', description: 'Options AMM' },
  { id: 'ANCIENT8', name: 'Ancient8', symbol: 'A8', icon: '8️⃣', color: '#FF6B00', category: 'Layer2', explorer: 'scan.ancient8.gg', description: 'Gaming L2' },
  { id: 'PARADEX', name: 'Paradex', symbol: 'PARA', icon: '📈', color: '#5B21B6', category: 'Layer2', explorer: 'explorer.paradex.trade', description: 'Perpetuals DEX' },
  { id: 'REDDIO', name: 'Reddio', symbol: 'REDT', icon: '🔴', color: '#FF4444', category: 'Layer2', explorer: 'explorer.reddio.com', description: 'ZK-rollup' },
  { id: 'HYPR', name: 'Hypr Network', symbol: 'HYPR', icon: '⚡', color: '#00FFFF', category: 'Layer2', explorer: 'explorer.hypr.network', description: 'High-performance L2' },
  { id: 'MINT', name: 'Mint Blockchain', symbol: 'MINT', icon: '🌿', color: '#00C853', category: 'Layer2', explorer: 'explorer.mintchain.io', description: 'NFT L2' },
  { id: 'XTERIO', name: 'Xterio', symbol: 'XTER', icon: '🎮', color: '#9C27B0', category: 'Layer2', explorer: 'xterscan.io', description: 'Gaming ecosystem' },
  { id: 'REDSTONE', name: 'Redstone', symbol: 'RED', icon: '🔴', color: '#DC143C', category: 'Layer2', explorer: 'explorer.redstone.xyz', description: 'Gaming L2' },
  { id: 'APEX', name: 'ApeX Protocol', symbol: 'APEX', icon: '🔺', color: '#FF6B35', category: 'Layer2', explorer: 'explorer.apex.exchange', description: 'Derivatives DEX' },
  { id: 'MYRIA', name: 'Myria', symbol: 'MYRIA', icon: '🎮', color: '#F5A623', category: 'Layer2', explorer: 'explorer.myria.com', description: 'Gaming L2' },
  { id: 'DEBANK', name: 'DeBank Chain', symbol: 'DB', icon: '🏦', color: '#5B8FF9', category: 'Layer2', explorer: 'explorer.debank.com', description: 'Social L2' },
  { id: 'FRAME', name: 'Frame', symbol: 'FRAME', icon: '🖼️', color: '#000000', category: 'Layer2', explorer: 'explorer.frame.xyz', description: 'Identity L2' },
  { id: 'CYBER', name: 'Cyber', symbol: 'CYBER', icon: '🌐', color: '#00FF00', category: 'Layer2', explorer: 'cyberscan.co', description: 'Social L2' },
  { id: 'HAM', name: 'Ham Chain', symbol: 'HAM', icon: '🍖', color: '#FF69B4', category: 'Layer2', explorer: 'explorer.ham.fun', description: 'Meme L2' },
  
  // Sidechains & Alt L1s (50+ chains)
  { id: 'BNB_CHAIN', name: 'BNB Chain', symbol: 'BNB', icon: '◆', color: '#F3BA2F', category: 'Sidechain', explorer: 'bscscan.com', description: 'Binance ecosystem' },
  { id: 'CRONOS', name: 'Cronos', symbol: 'CRO', icon: '🦁', color: '#002D74', category: 'Sidechain', explorer: 'cronoscan.com', description: 'Crypto.com chain' },
  { id: 'RONIN', name: 'Ronin', symbol: 'RON', icon: '⚔️', color: '#1273EA', category: 'Sidechain', explorer: 'app.roninchain.com', description: 'Gaming sidechain' },
  { id: 'AURORA', name: 'Aurora', symbol: 'AURORA', icon: '🌅', color: '#70D44B', category: 'Layer2', explorer: 'aurorascan.dev', description: 'NEAR EVM' },
  { id: 'GNOSIS', name: 'Gnosis Chain', symbol: 'XDAI', icon: '🦉', color: '#04795B', category: 'Sidechain', explorer: 'gnosisscan.io', description: 'Stable payments' },
  { id: 'FUSE', name: 'Fuse', symbol: 'FUSE', icon: '⚡', color: '#B4FA3C', category: 'Sidechain', explorer: 'explorer.fuse.io', description: 'Mobile payments' },
  { id: 'EVMOS_EVM', name: 'Evmos EVM', symbol: 'EVMOS', icon: '🔥', color: '#ED4E33', category: 'Sidechain', explorer: 'evm.evmos.org', description: 'Cosmos EVM' },
  { id: 'KAVA_EVM', name: 'Kava EVM', symbol: 'KAVA', icon: '🌿', color: '#FF564F', category: 'Sidechain', explorer: 'explorer.kava.io', description: 'Kava EVM co-chain' },
  { id: 'CANTO_EVM', name: 'Canto EVM', symbol: 'CANTO', icon: '🎵', color: '#06FC99', category: 'Sidechain', explorer: 'evm.explorer.canto.io', description: 'Free public infra' },
  { id: 'METER', name: 'Meter', symbol: 'MTRG', icon: '⚡', color: '#1A1A2E', category: 'Layer1', explorer: 'scan.meter.io', description: 'High-performance PoW' },
  { id: 'SYSCOIN', name: 'Syscoin', symbol: 'SYS', icon: '🔷', color: '#0082C6', category: 'Layer1', explorer: 'explorer.syscoin.org', description: 'Bitcoin merge-mined' },
  { id: 'VELAS', name: 'Velas', symbol: 'VLX', icon: '🚀', color: '#0033FF', category: 'Layer1', explorer: 'evmexplorer.velas.com', description: 'AI-powered blockchain' },
  { id: 'WANCHAIN', name: 'Wanchain', symbol: 'WAN', icon: '🌐', color: '#136AAD', category: 'Layer1', explorer: 'wanscan.org', description: 'Cross-chain infrastructure' },
  { id: 'THUNDERCORE', name: 'ThunderCore', symbol: 'TT', icon: '⚡', color: '#FCC100', category: 'Layer1', explorer: 'viewblock.io/thundercore', description: 'Fast EVM' },
  { id: 'TOMOCHAIN', name: 'TomoChain', symbol: 'TOMO', icon: '⚡', color: '#6C3FE4', category: 'Layer1', explorer: 'tomoscan.io', description: 'Scalable blockchain' },
  { id: 'HECO', name: 'Huobi ECO Chain', symbol: 'HT', icon: '🔥', color: '#2E7BF6', category: 'Sidechain', explorer: 'hecoinfo.com', description: 'Huobi ecosystem' },
  { id: 'OKXCHAIN', name: 'OKX Chain', symbol: 'OKT', icon: '⭕', color: '#000000', category: 'Sidechain', explorer: 'www.oklink.com/okc', description: 'OKX ecosystem' },
  { id: 'KUCOIN', name: 'KuCoin Community Chain', symbol: 'KCS', icon: '🟢', color: '#23AF91', category: 'Sidechain', explorer: 'explorer.kcc.io', description: 'KuCoin ecosystem' },
  { id: 'BITGERT', name: 'Bitgert', symbol: 'BRISE', icon: '🔥', color: '#FFD700', category: 'Layer1', explorer: 'brisescan.com', description: 'Zero gas fees' },
  { id: 'CORE', name: 'Core', symbol: 'CORE', icon: '🔴', color: '#FF9500', category: 'Layer1', explorer: 'scan.coredao.org', description: 'Bitcoin-powered' },
  { id: 'CONFLUX', name: 'Conflux', symbol: 'CFX', icon: '🌊', color: '#4A90E2', category: 'Layer1', explorer: 'confluxscan.io', description: 'Tree-graph consensus' },
  { id: 'AION', name: 'Aion', symbol: 'AION', icon: '⚛️', color: '#00BFFF', category: 'Layer1', explorer: 'mainnet.aion.network', description: 'Multi-tier blockchain' },
  { id: 'ENERGI', name: 'Energi', symbol: 'NRG', icon: '⚡', color: '#00D494', category: 'Layer1', explorer: 'explorer.energi.network', description: 'Self-funding treasury' },
  { id: 'GOCHAIN', name: 'GoChain', symbol: 'GO', icon: '🚀', color: '#2AB930', category: 'Layer1', explorer: 'explorer.gochain.io', description: 'Scalable Ethereum' },
  { id: 'ELASTOS', name: 'Elastos', symbol: 'ELA', icon: '🔷', color: '#4A90E2', category: 'Layer1', explorer: 'blockchain.elastos.io', description: 'SmartWeb platform' },
  { id: 'NULS', name: 'NULS', symbol: 'NULS', icon: '🟢', color: '#82C341', category: 'Layer1', explorer: 'nulscan.io', description: 'Modular blockchain' },
  { id: 'ARDOR', name: 'Ardor', symbol: 'ARDR', icon: '🔷', color: '#1162A1', category: 'Layer1', explorer: 'ardor.tools', description: 'Parent-child chains' },
  { id: 'STRATIS', name: 'Stratis', symbol: 'STRAX', icon: '🔷', color: '#1387C9', category: 'Layer1', explorer: 'explorer.stratisplatform.com', description: 'Enterprise blockchain' },
  { id: 'ARK', name: 'Ark', symbol: 'ARK', icon: '🚀', color: '#F70000', category: 'Layer1', explorer: 'explorer.ark.io', description: 'Blockchain ecosystem' },
  { id: 'LISK', name: 'Lisk', symbol: 'LSK', icon: '🔷', color: '#0D4EA0', category: 'Layer1', explorer: 'lisk.observer', description: 'JavaScript blockchain' },
  { id: 'NEM', name: 'NEM', symbol: 'XEM', icon: '🔷', color: '#67B2E8', category: 'Layer1', explorer: 'explorer.nemtool.com', description: 'Smart asset blockchain' },
  { id: 'SYMBOL', name: 'Symbol', symbol: 'XYM', icon: '⚡', color: '#67B2E8', category: 'Layer1', explorer: 'symbol.fyi', description: 'Enterprise blockchain' },
  { id: 'KOMODO', name: 'Komodo', symbol: 'KMD', icon: '🐉', color: '#2B6680', category: 'Layer1', explorer: 'kmdexplorer.io', description: 'Multi-chain platform' },
  { id: 'PIVX', name: 'PIVX', symbol: 'PIVX', icon: '🔒', color: '#5E4C9F', category: 'Layer1', explorer: 'explorer.pivx.org', description: 'Privacy coin' },
  { id: 'NAVCOIN', name: 'NavCoin', symbol: 'NAV', icon: '🧭', color: '#7D59B5', category: 'Layer1', explorer: 'www.navexplorer.com', description: 'Privacy-focused' },
  { id: 'VERGE', name: 'Verge', symbol: 'XVG', icon: '🔒', color: '#00CBFF', category: 'Layer1', explorer: 'verge-blockchain.info', description: 'Privacy coin' },
  { id: 'HORIZEN', name: 'Horizen', symbol: 'ZEN', icon: '🔷', color: '#041742', category: 'Layer1', explorer: 'explorer.horizen.io', description: 'Zero-knowledge sidechain' },
  { id: 'BEAM', name: 'Beam', symbol: 'BEAM', icon: '💎', color: '#0B76FF', category: 'Layer1', explorer: 'explorer.beam.mw', description: 'Mimblewimble privacy' },
  { id: 'GRIN', name: 'Grin', symbol: 'GRIN', icon: '😁', color: '#FFF000', category: 'Layer1', explorer: 'grin.blockscan.com', description: 'Mimblewimble' },
  { id: 'DECRED', name: 'Decred', symbol: 'DCR', icon: '🔷', color: '#2ED6A1', category: 'Layer1', explorer: 'dcrdata.decred.org', description: 'Hybrid PoW/PoS' },
  { id: 'DIGIBYTE', name: 'DigiByte', symbol: 'DGB', icon: '🔷', color: '#006AD2', category: 'Layer1', explorer: 'digiexplorer.info', description: 'Secure UTXO' },
  { id: 'RAVENCOIN', name: 'Ravencoin', symbol: 'RVN', icon: '🦅', color: '#384182', category: 'Layer1', explorer: 'ravencoin.network', description: 'Asset transfer' },
  { id: 'VERTCOIN', name: 'Vertcoin', symbol: 'VTC', icon: '🟢', color: '#1B5E20', category: 'Layer1', explorer: 'insight.vertcoin.org', description: 'ASIC-resistant' },
  { id: 'ERGO', name: 'Ergo', symbol: 'ERG', icon: '🔷', color: '#FF5722', category: 'Layer1', explorer: 'explorer.ergoplatform.com', description: 'Contractual money' },
  { id: 'NERVOS', name: 'Nervos Network', symbol: 'CKB', icon: '🧠', color: '#3CC68A', category: 'Layer1', explorer: 'explorer.nervos.org', description: 'Layered architecture' },
  { id: 'KADENA', name: 'Kadena', symbol: 'KDA', icon: '⛓️', color: '#ED098F', category: 'Layer1', explorer: 'explorer.chainweb.com', description: 'Braided chains' },
  { id: 'FLUX', name: 'Flux', symbol: 'FLUX', icon: '⚡', color: '#2B6CB0', category: 'Layer1', explorer: 'explorer.runonflux.io', description: 'Decentralized cloud' },
  { id: 'ALEPHIUM', name: 'Alephium', symbol: 'ALPH', icon: '🔷', color: '#FF0000', category: 'Layer1', explorer: 'explorer.alephium.org', description: 'Sharded L1' },
  { id: 'KASPA', name: 'Kaspa', symbol: 'KAS', icon: '💎', color: '#70C7BA', category: 'Layer1', explorer: 'explorer.kaspa.org', description: 'BlockDAG' },
  { id: 'ALEO', name: 'Aleo', symbol: 'ALEO', icon: '🔒', color: '#000000', category: 'Layer1', explorer: 'aleo.network', description: 'Zero-knowledge privacy' },
  
  // Gaming & Metaverse Chains (30+ chains)
  { id: 'IMMUTABLE_ZKEVM', name: 'Immutable zkEVM', symbol: 'IMX', icon: '🎮', color: '#0B0E11', category: 'Layer2', explorer: 'explorer.immutable.com', description: 'Gaming zkEVM' },
  { id: 'GALA', name: 'Gala Games', symbol: 'GALA', icon: '🎮', color: '#FF6B00', category: 'Layer1', explorer: 'explorer.gala.com', description: 'Gaming ecosystem' },
  { id: 'ENJIN', name: 'Enjin', symbol: 'ENJ', icon: '🎮', color: '#7866D5', category: 'Layer1', explorer: 'enjin.subscan.io', description: 'Gaming NFTs' },
  { id: 'EFINITY', name: 'Efinity', symbol: 'EFI', icon: '♾️', color: '#7866D5', category: 'Layer1', explorer: 'efinity.subscan.io', description: 'NFT parachain' },
  { id: 'WAX', name: 'WAX', symbol: 'WAXP', icon: '🎮', color: '#F89022', category: 'Layer1', explorer: 'waxblock.io', description: 'NFT marketplace' },
  { id: 'ULTRA', name: 'Ultra', symbol: 'UOS', icon: '🎮', color: '#7B5FFF', category: 'Layer1', explorer: 'explorer.ultra.io', description: 'Gaming distribution' },
  { id: 'IOTEX', name: 'IoTeX', symbol: 'IOTX', icon: '🔷', color: '#00D4AA', category: 'Layer1', explorer: 'iotexscan.io', description: 'IoT blockchain' },
  { id: 'SANDBOX', name: 'The Sandbox', symbol: 'SAND', icon: '🏖️', color: '#04ADEF', category: 'Layer1', explorer: 'polygonscan.com', description: 'Metaverse platform' },
  { id: 'DECENTRALAND', name: 'Decentraland', symbol: 'MANA', icon: '🌐', color: '#FF2D55', category: 'Layer1', explorer: 'etherscan.io', description: 'Virtual world' },
  { id: 'AXIE', name: 'Axie Infinity', symbol: 'AXS', icon: '🎮', color: '#0055D5', category: 'Layer1', explorer: 'explorer.roninchain.com', description: 'Play-to-earn' },
  { id: 'ILLUVIUM', name: 'Illuvium', symbol: 'ILV', icon: '🎮', color: '#F89D28', category: 'Layer1', explorer: 'etherscan.io', description: 'RPG game' },
  { id: 'GODS', name: 'Gods Unchained', symbol: 'GODS', icon: '🃏', color: '#1E1E1E', category: 'Layer1', explorer: 'immutascan.io', description: 'Trading card game' },
  { id: 'STAR_ATLAS', name: 'Star Atlas', symbol: 'ATLAS', icon: '🚀', color: '#000000', category: 'Layer1', explorer: 'solscan.io', description: 'Space metaverse' },
  { id: 'BIGTIME', name: 'Big Time', symbol: 'BIGTIME', icon: '⏰', color: '#FFD700', category: 'Layer1', explorer: 'etherscan.io', description: 'Action RPG' },
  { id: 'TREASURE', name: 'Treasure', symbol: 'MAGIC', icon: '🏴‍☠️', color: '#DC2626', category: 'Layer1', explorer: 'arbiscan.io', description: 'Gaming ecosystem' },
  { id: 'BEAM_GAMING', name: 'Beam Gaming', symbol: 'BEAM', icon: '🎮', color: '#9333EA', category: 'Layer1', explorer: 'subnets.avax.network/beam', description: 'Gaming subnet' },
  { id: 'XPLA', name: 'XPLA', symbol: 'XPLA', icon: '🎮', color: '#00B8D4', category: 'Layer1', explorer: 'explorer.xpla.io', description: 'Gaming blockchain' },
  { id: 'OASYS', name: 'Oasys', symbol: 'OAS', icon: '🎮', color: '#00D4AA', category: 'Layer1', explorer: 'scan.oasys.games', description: 'Gaming optimized' },
  { id: 'HOME_VERSE', name: 'HOME Verse', symbol: 'HOME', icon: '🏠', color: '#FF6B35', category: 'Sidechain', explorer: 'explorer.oasys.homeverse.games', description: 'Oasys verse' },
  { id: 'MCH_VERSE', name: 'MCH Verse', symbol: 'MCHC', icon: '⚔️', color: '#4169E1', category: 'Sidechain', explorer: 'explorer.oasys.mycryptoheroes.net', description: 'Gaming verse' },
  { id: 'DEFI_KINGDOMS', name: 'DeFi Kingdoms', symbol: 'JEWEL', icon: '💎', color: '#4ADE80', category: 'Sidechain', explorer: 'subnets.avax.network/defi-kingdoms', description: 'GameFi' },
  { id: 'SWIMMER', name: 'Swimmer Network', symbol: 'SWIMMER', icon: '🏊', color: '#06B6D4', category: 'Sidechain', explorer: 'explorer.swimmer.network', description: 'Gaming subnet' },
  { id: 'SHRAPNEL', name: 'Shrapnel', symbol: 'SHRAP', icon: '💥', color: '#DC2626', category: 'Layer2', explorer: 'explorer.shrapnel.com', description: 'FPS game' },
  { id: 'GUNZILLA', name: 'Gunzilla', symbol: 'GUN', icon: '🔫', color: '#000000', category: 'Layer1', explorer: 'explorer.gunzilla.io', description: 'Gaming blockchain' },
  { id: 'GALA_FILM', name: 'Gala Film', symbol: 'FILM', icon: '🎬', color: '#FF6B00', category: 'Layer1', explorer: 'explorer.gala.film', description: 'Entertainment' },
  { id: 'GALA_MUSIC', name: 'Gala Music', symbol: 'MUSIC', icon: '🎵', color: '#FF6B00', category: 'Layer1', explorer: 'explorer.gala.music', description: 'Music platform' },
  { id: 'VULCAN', name: 'Vulcan Forged', symbol: 'PYR', icon: '🔥', color: '#E63946', category: 'Layer1', explorer: 'explorer.vulcanforged.com', description: 'Gaming studio' },
  { id: 'MOBOX', name: 'MOBOX', symbol: 'MBOX', icon: '📦', color: '#FFD700', category: 'Layer1', explorer: 'bscscan.com', description: 'GameFi platform' },
  { id: 'ALTURA', name: 'Altura', symbol: 'ALU', icon: '🎮', color: '#6366F1', category: 'Layer1', explorer: 'bscscan.com', description: 'Gaming NFTs' },
  { id: 'SIDUS', name: 'Sidus Heroes', symbol: 'SIDUS', icon: '🚀', color: '#8B5CF6', category: 'Layer1', explorer: 'etherscan.io', description: 'Space metaverse' },
  
  // DeFi Specialized Chains (30+ chains)
  { id: 'THORCHAIN', name: 'THORChain', symbol: 'RUNE', icon: 'ᚦ', color: '#00CCAB', category: 'Layer1', explorer: 'viewblock.io/thorchain', description: 'Cross-chain DEX' },
  { id: 'MAYA', name: 'Maya Protocol', symbol: 'CACAO', icon: '🌿', color: '#00D4AA', category: 'Layer1', explorer: 'www.mayascan.org', description: 'THORChain fork' },
  { id: 'PENDLE', name: 'Pendle', symbol: 'PENDLE', icon: '📊', color: '#00D4AA', category: 'Layer1', explorer: 'etherscan.io', description: 'Yield trading' },
  { id: 'RADIX', name: 'Radix', symbol: 'XRD', icon: '◉', color: '#00C389', category: 'Layer1', explorer: 'dashboard.radixdlt.com', description: 'DeFi-focused' },
  { id: 'FLARE', name: 'Flare', symbol: 'FLR', icon: '🔥', color: '#E63946', category: 'Layer1', explorer: 'flare-explorer.flare.network', description: 'Data oracle' },
  { id: 'SONGBIRD', name: 'Songbird', symbol: 'SGB', icon: '🐦', color: '#FFD700', category: 'Layer1', explorer: 'songbird-explorer.flare.network', description: 'Flare canary' },
  { id: 'XDC', name: 'XDC Network', symbol: 'XDC', icon: '🔷', color: '#0C4DA2', category: 'Layer1', explorer: 'xdcscan.io', description: 'Trade finance' },
  { id: 'VITE', name: 'Vite', symbol: 'VITE', icon: '⚡', color: '#007AFF', category: 'Layer1', explorer: 'vitescan.io', description: 'DAG smart contracts' },
  { id: 'REEF', name: 'Reef', symbol: 'REEF', icon: '🪸', color: '#7B2BF9', category: 'Layer1', explorer: 'reefscan.com', description: 'DeFi platform' },
  { id: 'ACALA_EVM', name: 'Acala EVM', symbol: 'ACA', icon: '🦀', color: '#E40C5B', category: 'Sidechain', explorer: 'blockscout.acala.network', description: 'Polkadot DeFi' },
  { id: 'KARURA_EVM', name: 'Karura EVM', symbol: 'KAR', icon: '🦐', color: '#FF4C3B', category: 'Sidechain', explorer: 'blockscout.karura.network', description: 'Kusama DeFi' },
  { id: 'ASTAR_EVM', name: 'Astar EVM', symbol: 'ASTR', icon: '⭐', color: '#0AE2FF', category: 'Sidechain', explorer: 'blockscout.com/astar', description: 'Polkadot dApps' },
  { id: 'SHIDEN', name: 'Shiden', symbol: 'SDN', icon: '🌟', color: '#FF1493', category: 'Layer1', explorer: 'shiden.subscan.io', description: 'Kusama dApps' },
  { id: 'CLOVER', name: 'Clover', symbol: 'CLV', icon: '🍀', color: '#00D4AA', category: 'Layer1', explorer: 'clover.subscan.io', description: 'Cross-chain DeFi' },
  { id: 'EQUILIBRIUM', name: 'Equilibrium', symbol: 'EQ', icon: '⚖️', color: '#00D4AA', category: 'Layer1', explorer: 'equilibrium.subscan.io', description: 'DeFi one-stop' },
  { id: 'GENSHIRO', name: 'Genshiro', symbol: 'GENS', icon: '⚖️', color: '#FF4081', category: 'Layer1', explorer: 'genshiro.subscan.io', description: 'Kusama DeFi' },
  { id: 'CALAMARI', name: 'Calamari', symbol: 'KMA', icon: '🦑', color: '#FF6B35', category: 'Layer1', explorer: 'calamari.subscan.io', description: 'Privacy parachain' },
  { id: 'MANTA_ATLANTIC', name: 'Manta Atlantic', symbol: 'MANTA', icon: '🧜', color: '#1B4965', category: 'Layer1', explorer: 'manta.subscan.io', description: 'Privacy DeFi' },
  { id: 'NODLE', name: 'Nodle', symbol: 'NODL', icon: '📡', color: '#00D4AA', category: 'Layer1', explorer: 'nodle.subscan.io', description: 'IoT network' },
  { id: 'ZEITGEIST', name: 'Zeitgeist', symbol: 'ZTG', icon: '🔮', color: '#E63946', category: 'Layer1', explorer: 'zeitgeist.subscan.io', description: 'Prediction markets' },
  { id: 'BASILISK', name: 'Basilisk', symbol: 'BSX', icon: '🦎', color: '#00FF00', category: 'Layer1', explorer: 'basilisk.subscan.io', description: 'Liquidity protocol' },
  { id: 'HYDRADX', name: 'HydraDX', symbol: 'HDX', icon: '💧', color: '#00D4AA', category: 'Layer1', explorer: 'hydradx.subscan.io', description: 'Omnipool DEX' },
  { id: 'PICASSO', name: 'Picasso', symbol: 'PICA', icon: '🎨', color: '#FF1493', category: 'Layer1', explorer: 'picasso.subscan.io', description: 'DeFi infrastructure' },
  { id: 'COMPOSABLE_COSMOS', name: 'Composable Cosmos', symbol: 'PICA', icon: '🎨', color: '#FF1493', category: 'Layer1', explorer: 'explorer.composable.finance', description: 'IBC DeFi' },
  { id: 'TURING', name: 'Turing Network', symbol: 'TUR', icon: '🤖', color: '#00D4AA', category: 'Layer1', explorer: 'turing.subscan.io', description: 'Automation' },
  { id: 'MANGATA', name: 'Mangata', symbol: 'MGX', icon: '🌊', color: '#00D4AA', category: 'Layer1', explorer: 'mangata.subscan.io', description: 'MEV-resistant DEX' },
  { id: 'HEIKO', name: 'Heiko', symbol: 'HKO', icon: '🦀', color: '#FF6B35', category: 'Layer1', explorer: 'heiko.subscan.io', description: 'Parallel on Kusama' },
  { id: 'ALTAIR', name: 'Altair', symbol: 'AIR', icon: '🌟', color: '#FFD700', category: 'Layer1', explorer: 'altair.subscan.io', description: 'Centrifuge on Kusama' },
  { id: 'KHALA', name: 'Khala', symbol: 'PHA', icon: '🔐', color: '#CDFA50', category: 'Layer1', explorer: 'khala.subscan.io', description: 'Phala on Kusama' },
  { id: 'KINTSUGI_BTC', name: 'Kintsugi BTC', symbol: 'KBTC', icon: '₿', color: '#ECC13A', category: 'Layer1', explorer: 'kintsugi.subscan.io', description: 'Wrapped Bitcoin' },
  
  // Emerging & Testnet Chains (40+ chains)
  { id: 'BERACHAIN', name: 'Berachain', symbol: 'BERA', icon: '🐻', color: '#FF6B35', category: 'Layer1', explorer: 'beratrail.io', description: 'Liquidity proof-of-stake' },
  { id: 'MONAD', name: 'Monad', symbol: 'MONAD', icon: '🔷', color: '#7B2BF9', category: 'Layer1', explorer: 'monad.xyz', description: 'Parallel EVM' },
  { id: 'FUEL', name: 'Fuel', symbol: 'FUEL', icon: '⛽', color: '#00F58C', category: 'Layer2', explorer: 'fuellabs.github.io', description: 'Modular execution' },
  { id: 'ECLIPSE', name: 'Eclipse', symbol: 'ECLIPSE', icon: '🌑', color: '#000000', category: 'Layer2', explorer: 'explorer.eclipse.xyz', description: 'Solana SVM L2' },
  { id: 'MOVEMENT', name: 'Movement', symbol: 'MOVE', icon: '🏃', color: '#00D4AA', category: 'Layer2', explorer: 'explorer.movementlabs.xyz', description: 'Move-based L2' },
  { id: 'ARTELA', name: 'Artela', symbol: 'ART', icon: '🎨', color: '#FF1493', category: 'Layer1', explorer: 'explorer.artela.network', description: 'Extensible blockchain' },
  { id: 'INITIA', name: 'Initia', symbol: 'INIT', icon: '🚀', color: '#00D4AA', category: 'Layer1', explorer: 'scan.initia.xyz', description: 'Interwoven rollups' },
  { id: 'BABYLON', name: 'Babylon', symbol: 'BBN', icon: '🏛️', color: '#FFD700', category: 'Layer1', explorer: 'babylonscan.io', description: 'Bitcoin staking' },
  { id: 'AVAIL', name: 'Avail', symbol: 'AVAIL', icon: '🔷', color: '#00D4AA', category: 'Layer1', explorer: 'explorer.avail.so', description: 'Data availability' },
  { id: 'ESPRESSO', name: 'Espresso', symbol: 'ESPR', icon: '☕', color: '#6F4E37', category: 'Layer1', explorer: 'explorer.espresso.network', description: 'Sequencing layer' },
  { id: 'EIGENLAYER', name: 'EigenLayer', symbol: 'EIGEN', icon: '🔷', color: '#00D4AA', category: 'Layer1', explorer: 'explorer.eigenlayer.xyz', description: 'Restaking protocol' },
  { id: 'ETHOS', name: 'Ethos', symbol: 'ETHOS', icon: '🌟', color: '#7B2BF9', category: 'Layer1', explorer: 'explorer.ethos.xyz', description: 'Universal wallet' },
  { id: 'LUMIA', name: 'Lumia', symbol: 'LUMIA', icon: '💡', color: '#FFD700', category: 'Layer1', explorer: 'explorer.lumia.org', description: 'Liquidity layer' },
  { id: 'MORPH', name: 'Morph', symbol: 'MORPH', icon: '🔄', color: '#00D4AA', category: 'Layer2', explorer: 'explorer.morphl2.io', description: 'Consumer crypto L2' },
  { id: 'ABSTRACT', name: 'Abstract', symbol: 'ABS', icon: '🎨', color: '#FF1493', category: 'Layer2', explorer: 'explorer.abs.xyz', description: 'Culture & creativity' },
  { id: 'STORY', name: 'Story Protocol', symbol: 'STORY', icon: '📖', color: '#7B2BF9', category: 'Layer1', explorer: 'explorer.story.foundation', description: 'IP blockchain' },
  { id: 'PLUME', name: 'Plume', symbol: 'PLUME', icon: '🪶', color: '#00D4AA', category: 'Layer1', explorer: 'explorer.plumenetwork.xyz', description: 'RWA chain' },
  { id: 'SONEIUM', name: 'Soneium', symbol: 'SONE', icon: '🎵', color: '#FF6B35', category: 'Layer2', explorer: 'explorer.soneium.org', description: 'Sony blockchain' },
  { id: 'UNICHAIN', name: 'Unichain', symbol: 'UNI', icon: '🦄', color: '#FF007A', category: 'Layer2', explorer: 'unichain.org', description: 'Uniswap L2' },
  { id: 'WORLDCHAIN', name: 'World Chain', symbol: 'WLD', icon: '🌍', color: '#000000', category: 'Layer2', explorer: 'worldscan.org', description: 'World ID chain' },
  { id: 'LENS', name: 'Lens Network', symbol: 'LENS', icon: '🌿', color: '#00501E', category: 'Layer1', explorer: 'explorer.lens.xyz', description: 'Social graph' },
  { id: 'FARCASTER', name: 'Farcaster', symbol: 'FCAST', icon: '🎭', color: '#7B2BF9', category: 'Layer2', explorer: 'explorer.farcaster.xyz', description: 'Social protocol' },
  { id: 'FRIEND_TECH', name: 'Friend.tech', symbol: 'FRIEND', icon: '👥', color: '#00D4AA', category: 'Layer2', explorer: 'basescan.org', description: 'Social trading' },
  { id: 'DEGEN', name: 'Degen Chain', symbol: 'DEGEN', icon: '🎩', color: '#7B2BF9', category: 'Layer2', explorer: 'explorer.degen.tips', description: 'Meme L3' },
  { id: 'XION', name: 'Xion', symbol: 'XION', icon: '⚡', color: '#00D4AA', category: 'Layer1', explorer: 'explorer.xion.app', description: 'Generalized abstraction' },
  { id: 'BEVM', name: 'BEVM', symbol: 'BEVM', icon: '₿', color: '#F7931A', category: 'Layer2', explorer: 'scan.bevm.io', description: 'Bitcoin L2' },
  { id: 'BITLAYER', name: 'BitLayer', symbol: 'BTR', icon: '₿', color: '#F7931A', category: 'Layer2', explorer: 'bitlayer.org', description: 'Bitcoin L2' },
  { id: 'MERLIN', name: 'Merlin Chain', symbol: 'MERL', icon: '🧙', color: '#7B2BF9', category: 'Layer2', explorer: 'scan.merlinchain.io', description: 'Bitcoin L2' },
  { id: 'BOB', name: 'BOB', symbol: 'BOB', icon: '🔶', color: '#FF6B35', category: 'Layer2', explorer: 'explorer.gobob.xyz', description: 'Bitcoin L2' },
  { id: 'BSQUARED', name: 'B² Network', symbol: 'B2', icon: '₿', color: '#F7931A', category: 'Layer2', explorer: 'explorer.bsquared.network', description: 'Bitcoin L2' },
  { id: 'ROOTSTOCK', name: 'Rootstock', symbol: 'RBTC', icon: '₿', color: '#00A651', category: 'Sidechain', explorer: 'explorer.rsk.co', description: 'Bitcoin sidechain' },
  { id: 'LIQUID', name: 'Liquid Network', symbol: 'L-BTC', icon: '💧', color: '#00DACC', category: 'Sidechain', explorer: 'liquid.network', description: 'Bitcoin sidechain' },
  { id: 'STACKS', name: 'Stacks', symbol: 'STX', icon: '⚡', color: '#5546FF', category: 'Layer2', explorer: 'explorer.stacks.co', description: 'Bitcoin L2' },
  { id: 'FRACTAL', name: 'Fractal Bitcoin', symbol: 'FB', icon: '₿', color: '#F7931A', category: 'Layer2', explorer: 'explorer.fractalbitcoin.io', description: 'Bitcoin scaling' },
  { id: 'CITREA', name: 'Citrea', symbol: 'CTRX', icon: '🍋', color: '#FFD700', category: 'Layer2', explorer: 'explorer.citrea.xyz', description: 'Bitcoin ZK rollup' },
  { id: 'BOTANIX', name: 'Botanix', symbol: 'BTX', icon: '🌿', color: '#00D4AA', category: 'Layer2', explorer: 'explorer.botanixlabs.xyz', description: 'Bitcoin L2' },
  { id: 'ROLLUX', name: 'Rollux', symbol: 'SYS', icon: '🔷', color: '#0082C6', category: 'Layer2', explorer: 'explorer.rollux.com', description: 'Syscoin L2' },
  { id: 'NEON', name: 'Neon EVM', symbol: 'NEON', icon: '🌈', color: '#FF1493', category: 'Layer2', explorer: 'neonscan.org', description: 'Solana EVM' },
  { id: 'ECLIPSE_MAINNET', name: 'Eclipse Mainnet', symbol: 'ECLP', icon: '🌑', color: '#000000', category: 'Layer2', explorer: 'explorer.eclipse.xyz', description: 'Ethereum SVM' },
  { id: 'NITRO', name: 'Nitro', symbol: 'NITRO', icon: '⚡', color: '#00D4AA', category: 'Layer2', explorer: 'explorer.arbitrum.io/nitro', description: 'Arbitrum tech' },
  { id: 'NOVA', name: 'Arbitrum Nova', symbol: 'NOVA', icon: '⭐', color: '#28A0F0', category: 'Layer2', explorer: 'nova.arbiscan.io', description: 'Gaming L2' },
];

export const getBlockchainInfo = (id: string): BlockchainInfo | undefined => {
  return BLOCKCHAINS.find(b => b.id === id);
};

export const getBlockchainsByCategory = (category: string) => {
  return BLOCKCHAINS.filter(b => b.category === category);
};

export const getBlockchainColor = (id: string): string => {
  return getBlockchainInfo(id)?.color || '#6B7280';
};

export const getBlockchainIcon = (id: string): string => {
  return getBlockchainInfo(id)?.icon || '⬢';
};
