export const countries = [
  { code: 'AF', name: 'Afghanistan', cities: ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif'] },
  { code: 'AL', name: 'Albania', cities: ['Tirana', 'Durrës', 'Vlorë', 'Shkodër'] },
  { code: 'DZ', name: 'Algeria', cities: ['Algiers', 'Oran', 'Constantine', 'Annaba'] },
  { code: 'AR', name: 'Argentina', cities: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza'] },
  { code: 'AM', name: 'Armenia', cities: ['Yerevan', 'Gyumri', 'Vanadzor', 'Vagharshapat'] },
  { code: 'AU', name: 'Australia', cities: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide'] },
  { code: 'AT', name: 'Austria', cities: ['Vienna', 'Graz', 'Linz', 'Salzburg'] },
  { code: 'AZ', name: 'Azerbaijan', cities: ['Baku', 'Ganja', 'Sumqayit', 'Lankaran'] },
  { code: 'BH', name: 'Bahrain', cities: ['Manama', 'Riffa', 'Muharraq', 'Hamad Town'] },
  { code: 'BD', name: 'Bangladesh', cities: ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi'] },
  { code: 'BY', name: 'Belarus', cities: ['Minsk', 'Gomel', 'Mogilev', 'Vitebsk'] },
  { code: 'BE', name: 'Belgium', cities: ['Brussels', 'Antwerp', 'Ghent', 'Charleroi'] },
  { code: 'BO', name: 'Bolivia', cities: ['La Paz', 'Santa Cruz', 'Cochabamba', 'Sucre'] },
  { code: 'BA', name: 'Bosnia and Herzegovina', cities: ['Sarajevo', 'Banja Luka', 'Tuzla', 'Zenica'] },
  { code: 'BR', name: 'Brazil', cities: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Porto Alegre'] },
  { code: 'BG', name: 'Bulgaria', cities: ['Sofia', 'Plovdiv', 'Varna', 'Burgas'] },
  { code: 'KH', name: 'Cambodia', cities: ['Phnom Penh', 'Siem Reap', 'Battambang', 'Sihanoukville'] },
  { code: 'CM', name: 'Cameroon', cities: ['Yaoundé', 'Douala', 'Garoua', 'Bamenda'] },
  { code: 'CA', name: 'Canada', cities: ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Quebec City'] },
  { code: 'CL', name: 'Chile', cities: ['Santiago', 'Valparaíso', 'Concepción', 'La Serena'] },
  { code: 'CN', name: 'China', cities: ['Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Chengdu', 'Hangzhou', 'Wuhan', 'Xian', 'Chongqing', 'Tianjin'] },
  { code: 'CO', name: 'Colombia', cities: ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena'] },
  { code: 'CR', name: 'Costa Rica', cities: ['San José', 'Limón', 'Alajuela', 'Heredia'] },
  { code: 'HR', name: 'Croatia', cities: ['Zagreb', 'Split', 'Rijeka', 'Osijek'] },
  { code: 'CU', name: 'Cuba', cities: ['Havana', 'Santiago de Cuba', 'Camagüey', 'Holguín'] },
  { code: 'CY', name: 'Cyprus', cities: ['Nicosia', 'Limassol', 'Larnaca', 'Paphos'] },
  { code: 'CZ', name: 'Czech Republic', cities: ['Prague', 'Brno', 'Ostrava', 'Plzeň'] },
  { code: 'DK', name: 'Denmark', cities: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg'] },
  { code: 'DO', name: 'Dominican Republic', cities: ['Santo Domingo', 'Santiago', 'La Romana', 'San Pedro de Macorís'] },
  { code: 'EC', name: 'Ecuador', cities: ['Quito', 'Guayaquil', 'Cuenca', 'Santo Domingo'] },
  { code: 'EG', name: 'Egypt', cities: ['Cairo', 'Alexandria', 'Giza', 'Shubra El Kheima', 'Port Said'] },
  { code: 'SV', name: 'El Salvador', cities: ['San Salvador', 'Santa Ana', 'San Miguel', 'Soyapango'] },
  { code: 'EE', name: 'Estonia', cities: ['Tallinn', 'Tartu', 'Narva', 'Pärnu'] },
  { code: 'ET', name: 'Ethiopia', cities: ['Addis Ababa', 'Dire Dawa', 'Mekelle', 'Gondar'] },
  { code: 'FI', name: 'Finland', cities: ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu'] },
  { code: 'FR', name: 'France', cities: ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux'] },
  { code: 'GE', name: 'Georgia', cities: ['Tbilisi', 'Batumi', 'Kutaisi', 'Rustavi'] },
  { code: 'DE', name: 'Germany', cities: ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Stuttgart', 'Düsseldorf', 'Dortmund', 'Essen', 'Leipzig'] },
  { code: 'GH', name: 'Ghana', cities: ['Accra', 'Kumasi', 'Tamale', 'Sekondi-Takoradi'] },
  { code: 'GR', name: 'Greece', cities: ['Athens', 'Thessaloniki', 'Patras', 'Heraklion'] },
  { code: 'GT', name: 'Guatemala', cities: ['Guatemala City', 'Mixco', 'Villa Nueva', 'Quetzaltenango'] },
  { code: 'HN', name: 'Honduras', cities: ['Tegucigalpa', 'San Pedro Sula', 'Choloma', 'La Ceiba'] },
  { code: 'HK', name: 'Hong Kong', cities: ['Hong Kong', 'Kowloon', 'Tsuen Wan', 'Yuen Long'] },
  { code: 'HU', name: 'Hungary', cities: ['Budapest', 'Debrecen', 'Szeged', 'Miskolc'] },
  { code: 'IS', name: 'Iceland', cities: ['Reykjavik', 'Kópavogur', 'Hafnarfjörður', 'Akureyri'] },
  { code: 'IN', name: 'India', cities: ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata', 'Pune', 'Ahmedabad', 'Jaipur', 'Surat'] },
  { code: 'ID', name: 'Indonesia', cities: ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Semarang', 'Makassar', 'Palembang'] },
  { code: 'IR', name: 'Iran', cities: ['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Shiraz', 'Tabriz'] },
  { code: 'IQ', name: 'Iraq', cities: ['Baghdad', 'Basra', 'Mosul', 'Erbil', 'Najaf'] },
  { code: 'IE', name: 'Ireland', cities: ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford'] },
  { code: 'IL', name: 'Israel', cities: ['Jerusalem', 'Tel Aviv', 'Haifa', 'Rishon LeZion', 'Petah Tikva'] },
  { code: 'IT', name: 'Italy', cities: ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Venice'] },
  { code: 'JM', name: 'Jamaica', cities: ['Kingston', 'Spanish Town', 'Portmore', 'Montego Bay'] },
  { code: 'JP', name: 'Japan', cities: ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya', 'Sapporo', 'Fukuoka', 'Kobe', 'Kyoto', 'Kawasaki'] },
  { code: 'JO', name: 'Jordan', cities: ['Amman', 'Zarqa', 'Irbid', 'Russeifa'] },
  { code: 'KZ', name: 'Kazakhstan', cities: ['Almaty', 'Nur-Sultan', 'Shymkent', 'Karaganda'] },
  { code: 'KE', name: 'Kenya', cities: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret'] },
  { code: 'KW', name: 'Kuwait', cities: ['Kuwait City', 'Hawalli', 'Salmiya', 'Sabah Al Salem'] },
  { code: 'KG', name: 'Kyrgyzstan', cities: ['Bishkek', 'Osh', 'Jalal-Abad', 'Karakol'] },
  { code: 'LA', name: 'Laos', cities: ['Vientiane', 'Pakse', 'Savannakhet', 'Luang Prabang'] },
  { code: 'LV', name: 'Latvia', cities: ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava'] },
  { code: 'LB', name: 'Lebanon', cities: ['Beirut', 'Tripoli', 'Sidon', 'Tyre'] },
  { code: 'LY', name: 'Libya', cities: ['Tripoli', 'Benghazi', 'Misrata', 'Bayda'] },
  { code: 'LT', name: 'Lithuania', cities: ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai'] },
  { code: 'LU', name: 'Luxembourg', cities: ['Luxembourg City', 'Esch-sur-Alzette', 'Differdange', 'Dudelange'] },
  { code: 'MY', name: 'Malaysia', cities: ['Kuala Lumpur', 'George Town', 'Ipoh', 'Shah Alam', 'Johor Bahru'] },
  { code: 'MV', name: 'Maldives', cities: ['Malé', 'Addu City', 'Fuvahmulah', 'Kulhudhuffushi'] },
  { code: 'MX', name: 'Mexico', cities: ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'León', 'Cancún'] },
  { code: 'MD', name: 'Moldova', cities: ['Chișinău', 'Tiraspol', 'Bălți', 'Bender'] },
  { code: 'MC', name: 'Monaco', cities: ['Monaco', 'Monte Carlo', 'La Condamine', 'Fontvieille'] },
  { code: 'MN', name: 'Mongolia', cities: ['Ulaanbaatar', 'Erdenet', 'Darkhan', 'Choibalsan'] },
  { code: 'ME', name: 'Montenegro', cities: ['Podgorica', 'Nikšić', 'Pljevlja', 'Bijelo Polje'] },
  { code: 'MA', name: 'Morocco', cities: ['Casablanca', 'Rabat', 'Fes', 'Marrakech', 'Tangier'] },
  { code: 'MM', name: 'Myanmar', cities: ['Yangon', 'Mandalay', 'Naypyidaw', 'Mawlamyine'] },
  { code: 'NP', name: 'Nepal', cities: ['Kathmandu', 'Pokhara', 'Lalitpur', 'Bharatpur'] },
  { code: 'NL', name: 'Netherlands', cities: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven'] },
  { code: 'NZ', name: 'New Zealand', cities: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga'] },
  { code: 'NG', name: 'Nigeria', cities: ['Lagos', 'Kano', 'Ibadan', 'Abuja', 'Port Harcourt'] },
  { code: 'NO', name: 'Norway', cities: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Drammen'] },
  { code: 'OM', name: 'Oman', cities: ['Muscat', 'Salalah', 'Sohar', 'Nizwa'] },
  { code: 'PK', name: 'Pakistan', cities: ['Karachi', 'Lahore', 'Islamabad', 'Rawalpindi', 'Faisalabad', 'Multan'] },
  { code: 'PA', name: 'Panama', cities: ['Panama City', 'San Miguelito', 'Tocumen', 'David'] },
  { code: 'PY', name: 'Paraguay', cities: ['Asunción', 'Ciudad del Este', 'San Lorenzo', 'Luque'] },
  { code: 'PE', name: 'Peru', cities: ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Cusco'] },
  { code: 'PH', name: 'Philippines', cities: ['Manila', 'Quezon City', 'Davao', 'Cebu City', 'Makati'] },
  { code: 'PL', name: 'Poland', cities: ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań', 'Gdańsk'] },
  { code: 'PT', name: 'Portugal', cities: ['Lisbon', 'Porto', 'Braga', 'Coimbra', 'Funchal'] },
  { code: 'QA', name: 'Qatar', cities: ['Doha', 'Al Rayyan', 'Umm Salal', 'Al Wakrah'] },
  { code: 'RO', name: 'Romania', cities: ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța'] },
  { code: 'RU', name: 'Russia', cities: ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Kazan', 'Nizhny Novgorod'] },
  { code: 'SA', name: 'Saudi Arabia', cities: ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam'] },
  { code: 'RS', name: 'Serbia', cities: ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac'] },
  { code: 'SG', name: 'Singapore', cities: ['Singapore', 'Jurong', 'Woodlands', 'Tampines'] },
  { code: 'SK', name: 'Slovakia', cities: ['Bratislava', 'Košice', 'Prešov', 'Žilina'] },
  { code: 'SI', name: 'Slovenia', cities: ['Ljubljana', 'Maribor', 'Celje', 'Kranj'] },
  { code: 'ZA', name: 'South Africa', cities: ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth'] },
  { code: 'KR', name: 'South Korea', cities: ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju'] },
  { code: 'ES', name: 'Spain', cities: ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Málaga', 'Bilbao'] },
  { code: 'LK', name: 'Sri Lanka', cities: ['Colombo', 'Kandy', 'Galle', 'Jaffna'] },
  { code: 'SE', name: 'Sweden', cities: ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Västerås'] },
  { code: 'CH', name: 'Switzerland', cities: ['Zurich', 'Geneva', 'Basel', 'Lausanne', 'Bern'] },
  { code: 'SY', name: 'Syria', cities: ['Damascus', 'Aleppo', 'Homs', 'Latakia'] },
  { code: 'TW', name: 'Taiwan', cities: ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan'] },
  { code: 'TJ', name: 'Tajikistan', cities: ['Dushanbe', 'Khujand', 'Kulob', 'Qurghonteppa'] },
  { code: 'TZ', name: 'Tanzania', cities: ['Dar es Salaam', 'Mwanza', 'Arusha', 'Dodoma'] },
  { code: 'TH', name: 'Thailand', cities: ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Hat Yai'] },
  { code: 'TR', name: 'Turkey', cities: ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya', 'Adana'] },
  { code: 'TM', name: 'Turkmenistan', cities: ['Ashgabat', 'Türkmenabat', 'Daşoguz', 'Mary'] },
  { code: 'UG', name: 'Uganda', cities: ['Kampala', 'Gulu', 'Lira', 'Mbarara'] },
  { code: 'UA', name: 'Ukraine', cities: ['Kyiv', 'Kharkiv', 'Odesa', 'Dnipro', 'Lviv'] },
  { code: 'AE', name: 'United Arab Emirates', cities: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman', 'Ras Al Khaimah'] },
  { code: 'GB', name: 'United Kingdom', cities: ['London', 'Birmingham', 'Manchester', 'Glasgow', 'Liverpool', 'Edinburgh', 'Leeds'] },
  { code: 'US', name: 'United States', cities: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Miami', 'Seattle', 'Boston', 'Las Vegas', 'Atlanta'] },
  { code: 'UY', name: 'Uruguay', cities: ['Montevideo', 'Salto', 'Paysandú', 'Las Piedras'] },
  { code: 'UZ', name: 'Uzbekistan', cities: ['Tashkent', 'Samarkand', 'Namangan', 'Andijan'] },
  { code: 'VE', name: 'Venezuela', cities: ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto'] },
  { code: 'VN', name: 'Vietnam', cities: ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Hai Phong', 'Can Tho'] },
  { code: 'YE', name: 'Yemen', cities: ['Sana\'a', 'Aden', 'Taiz', 'Hodeidah'] },
  { code: 'ZM', name: 'Zambia', cities: ['Lusaka', 'Kitwe', 'Ndola', 'Kabwe'] },
  { code: 'ZW', name: 'Zimbabwe', cities: ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare'] }
];
